### ISSUE TITLE
Frequent PW Reset

### ISSUE THREAD

**Issue by jrbarronumd** [zachowj/xfinity-data-usage#13]
Thanks for your work and for sharing this project, it's crazy Comcast has made this so difficult, but I'm grateful to have a way to monitor our family's usage.

Has anyone else been having to reset their xfinity password every 2-4 days recently?  I used this container for a couple weeks with no issues, but about a week ago I had to reset my password, and now this morning was the 3rd time since then.  Is every 60 minutes too frequent to log in?  Doesn't seem like it should be.  I assume Comcast isn't singling me out here, so I was just wondering if anyone figured out a way to reduce this effect?

**Comment by zachowj** [comment]
I am seeing this same thing. Increasing the interval might delay the need to reset but haven't tested anything.

**Comment by jbrody17** [comment]
I originally had the delay set to 1 hour, PW would need to be reset after 3-4 days. I have it set to 8 hours now and it still needs to be reset after 3-4 days. I wouldn't need to track my usage if I had unlimited data... like I did 2 months ago.

**Comment by brian000** [comment]
I’m getting the same reset emails with the container set to poll every ten hours.

**Comment by janssenjones** [comment]
I bumped mine from hourly to every 8 hours, and my resets became less frequent.  I was needing to reset weekly, but managed to make it almost 3 weeks before they sent the next one.

**Comment by genem2** [comment]
Same here. Today I reset the pwd and reconfigured it for an 8hr updated - expecting to make it 24hours.  But even after resetting my password several times, verifying the new credentials in an incognito browser, updating the pwd in my config file, and removing and recreating the docker container, I'm not getting past:
````
Page Title: Sign in to Xfinity
Loading Usage https://customer.xfinity.com/apis/services/internet/usage
Not logged in
Loading (https://customer.xfinity.com)
Page Title: Sign in to Xfinity
Loading Usage https://customer.xfinity.com/apis/services/internet/usage
Not logged in
Loading (https://customer.xfinity.com)
Page Title: Sign in to Xfinity
Loading Usage https://customer.xfinity.com/apis/services/internet/usage
Browser Error: Error: Unable to login

**Comment by janssenjones** [comment]
This is now happening to me as well.  The app hasn't worked since yesterday.  I've been trying to determine if there's a way to increase logging to see why login is now failing.

**Comment by zachowj** [comment]
The page layout hasn't changed as far as I can tell. It still inputs the credentials in the correct locations and submits the form. My current guess is they added something to detect headless chrome and are blocking it.

**Comment by janssenjones** [comment]
Ugh....Comcast infuriates me.  They really don't want their customers to know how much data they are using! Thanks for all your work on this.

**Comment by jasii** [comment]
I started up this docker container for the first time today, got a password reset within 5 minutes.

**Comment by jrbarronumd** [comment]
Looks like it is working intermittently now.  I had no success for a couple days like the others posting here, and then today for a few hours it worked again.  Then tonight I got a PW reset email, and after I reset it, the login still fails after updating the config file.

**Comment by zachowj** [comment]
For me, it's working again and I haven't received an email to reset my password in over 15 days. Is it the same for others?

**Comment by jrbarronumd** [comment]
Same for me.  I'll close the issue.  Hopefully Comcast will be decent enough to allow us to check our own accounts for a while...

Thanks again @zachowj for sharing your efforts!
