### ISSUE TITLE
Unable to log in. State did not change error

### ISSUE THREAD

**Issue by jasii** [zachowj/xfinity-data-usage#130]
After upgrading to 20.2 I haven't been unable to log in. It was working after the first docker fix, but then after 20.1 or 20.2 it's been giving me a state did not change error.

In my config folder I just have my config.yml file

Here's the error

![xfinityerror](https://github.com/zachowj/xfinity-data-usage/assets/17171884/431cc2f0-69a2-43fb-bb1b-6b69c351d5de)

**Comment by gatlinnewhouse** [comment]
Got the same issue here, same logs as well

**Comment by zachowj** [comment]
Try stopping the container for 24 hours, then start it up again.

**Comment by gatlinnewhouse** [comment]
Mine happened when I ran the container for the first time

**Comment by jasii** [comment]
I stopped the container for about 30 hours and when I started it again I am still getting the same error.

**Comment by JoeDaddy7105** [comment]
I got the same error on initial startup. I got a 2FA text as soon as it started up but I do not see how I can enter the code so I am assuming this does not support 2FA accounts.

**Comment by jasii** [comment]
I've had the container running for the past month with it constantly failing. There would be few times it would actually update, but it would be about once a week between updates in usage. Then starting today on a new usage reset cycle it seems to be updating consistently.

Is it working again for anybody else here in this issue thread?

**Comment by jaredbarranco** [comment]
Just dropping a note here that it isn't working for me. Same error as noted above. My account is 2FA and I would guess that this isn't supported based on the below screenshot. Fails after entering password with a "Shouldn't be here, starting over" message.

<img width="813" alt="image" src="https://github.com/zachowj/xfinity-data-usage/assets/51723690/f019d925-d2f9-4b7b-a997-72d3a70ef83c">

If I have time, I'll try and get a PR together. Shouldn't be too difficult to have branching logic based on 2FA code window

**Comment by gatlinnewhouse** [comment]
> I've had the container running for the past month with it constantly failing. There would be few times it would actually update, but it would be about once a week between updates in usage. Then starting today on a new usage reset cycle it seems to be updating consistently.
> 
> Is it working again for anybody else here in this issue thread?

Still not working for me, even when I restart the container.

**Comment by raptor464** [comment]
It was working sporadically for me up until a week ago. I have the container running on a windows machine and a raspberry pi and both refuse to connect.
Raspberry Pi:
![image](https://github.com/zachowj/xfinity-data-usage/assets/143887337/2d8fde4b-7b96-4eb3-a7aa-b2287a96de81)

Windows:
![image](https://github.com/zachowj/xfinity-data-usage/assets/143887337/5474666b-e418-4dcf-8b87-78afbcf7e96e)

It used to work every once and a while on both machines.

**Comment by Vendo232** [comment]
it stopped working for me as well

![image](https://github.com/zachowj/xfinity-data-usage/assets/44098230/9e1f28dd-758f-4506-ab97-a3d1ea5c8409)

**Comment by derp90** [comment]
I am also getting this issue, first time running as well,

**Comment by gatlinnewhouse** [comment]
Can you try logging in to the website from a computer on the same network and then restarting the container?

**Comment by derp90** [comment]
> Can you try logging in to the website from a computer on the same network and then restarting the container?

I tried that and had the same result

**Comment by Vendo232** [comment]
> I'm still not getting consistent results.
> 
> Just letting it run gets the data usage once every 1-5 days
> 
> ![image](https://user-images.githubusercontent.com/32005229/280026498-4ae573a5-701a-4096-9988-867b8d6aea73.png)

what is your login frequency?

**Comment by derp90** [comment]
interval: 60
  pageTimeout: 300

**Comment by derp90** [comment]
I think that pageTimeout is not being used. No matter what value I set this to, it will instantly fail the 3 tries within a few seconds.
Currently set to 9999, I tried 600, and a few others with no difference.
@zachowj

**Comment by derp90** [comment]
Is it possible to expose a port to access chromium so I can try logging in directly into the container.
Something like this https://hub.docker.com/r/linuxserver/chromium

**Comment by zachowj** [comment]
It should be fixed in the latest release, v0.23.0.
