### ISSUE TITLE
Browser Error: TimeoutError: waiting for selector `#user` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by mitchsurp** [zachowj/xfinity-data-usage#20]
Getting this fancy new error when the container runs, and it's happening right after Xfinity forced another password reset. On resetting the password and running the latest, it fails to update and gives

`Browser Error: TimeoutError: waiting for selector `#user` failed: timeout 30000ms exceeded`

And I'm now newly unable to access the password reset site (or any login.xfinity.com page including oath.xfinity.com) from my WAN IP. If I connect on my phone with mobile data or using a VPN, it works correctly.

This is one heck of a game of cat and mouse Xfinity is playing, and them restricting my ability to log into my account at all (to check email, to pay my bill -- anything) might be what makes me pull the plug on this, as useful as it is.

**Comment by zachowj** [comment]
I haven't seen anything like it blocking my IP and I have it checking every 20 minutes.

**Comment by idmchris** [comment]
I am having this same issue, think I may have poked it too many times in the first x mins when I was struggling to get HA to detect the mqtt so I restarted the container a bunch.  Going to leave it a day to see if I get un-blocked, interestingly doesn't affect my ability to logon to xfinity though Chrome/UI (login.xfinity.com) like the previous poster.

Just figure I would leave a note here so if others get the same issue.  Will post back to let folks know if I get unblocked.
