### ISSUE TITLE
Xfinity Password reset no longer allows you to use past passwords

### ISSUE THREAD

**Issue by sepej** [zachowj/xfinity-data-usage#33]
IMAP password update started failing, so I tried to reset manually and I got this error:
"Your chosen password cannot be used, since you have used it in the past. Please select another password."

**Comment by zachowj** [comment]
Yes, I ran into this about a week ago and made a quick update for myself. 

I made it increment a 3 digit suffix onto my password. Which saves to file alongside the config file. I don't know how feasible that is for the general user. But going forward I think that is the only way the IMAP portion is going to still work.

**Comment by jasii** [comment]
It's as if Xfinity is reviewing all the changes you make to your repo and do something to counter it the next day...

That sounds like a pretty good option, though I feel like Xfinity will catch on and then next thing you know they won't allow you to use passwords that are similar to the previous passwords. I've seen that on a few other sites when creating a new password. Not sure if 3 digit suffix would be different enough if they end up making that a requirement in the future. Maybe generate a whole new password and save it alongside the config file, just to futureproof it a little more.

I feel like the general user who is able to set up the IMAP portion is savy enough to look at generated passwords in a password file that is set to save in the same folder as the config folder.

Thank you for your hard work on this project!

**Comment by zachowj** [comment]
Added
