### ISSUE TITLE
TimeoutError: waiting for selector `#passwd` failed

### ISSUE THREAD

**Issue by mvinci-wyze** [zachowj/xfinity-data-usage#54]
Good morning! I tried updating to 17.1 last night since 17.0 hadn't been working for me for a minute and when it pulled the image, I started getting a new timeout error.

2021-12-23 07:44:26 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 7:53:51 AM

**Comment by d2inco** [comment]
Why was this closed?  I'm experiencing the same thing.   Using the docker-hub image, so I know at least everything is set up correctly.

**Comment by xconverge** [comment]
I see the same thing too, sometimes when this happens, the cpu usage spikes and stays spiked until I restart the container

I setup a cronjob to restart this container nightly

@zachowj can you reopen this issue? or should I open a separate issue to start to look into it?
