### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by Dracoy** [zachowj/xfinity-data-usage#77]
New to docker but found your method, getting these issues, any idea what I could do to fix it? I spent time googling but couldn't get it to work.

2022-11-04 02:12:46 [error] : Unable to write cookies files. Error: EACCES: permission denied, open '/config/cookies.json' | stdout

2022-11-04 02:12:46 [error] : TypeError: Cannot read properties of undefined (reading 'length'). Next update at 3:12:31 AM | stdout

Also the http and post link IP addresses - I assume is the address of home assistant?

Thank you!

**Comment by xconverge** [comment]
For your permission issue, your volume (folder on disk) you are using has mismatched permissions with what the container is running as/trying to use

If you do a ```ls -la``` of the parent folder containing the directory you are trying to use, you will see the permissions and owner

You may need to use chmod and chown commands (probably with the recursive option) to resolve this

For the http and post questions, I would recommend skipping this for now (too many issues at once) until you get the container running smoothly and fetching usage. I personally dont use the http and post functionality and find it nice to just publish the data to mqtt

If you just leave http configured as ```http:``` then you can test this by just using a web browser to navigate to ```ipofdockerhost:portyouhaveforwardedto7878inconfig```

If you share your docker command or docker-compose entry you are using I could be more specific

**Comment by Dracoy** [comment]
Thank you! Let me look into this. This is 100% my issue, just new to docker and trying to learn it. Thanks again!
