### ISSUE TITLE
New user, unable to scrape since install (3 days and counting)

### ISSUE THREAD

**Issue by c3p0vsr2d2** [zachowj/xfinity-data-usage#90]
Tried everything in the comments, but I keep getting the following error:

Error: Execution context was destroyed, most likely because of a navigation.. Next update at 9:48:39 AM

This has been going on for 3 days now ..
I also already tried the 2FA switch ON and then switch OFF step without any success on the scraper.

Any other suggestions that I can try?

**Comment by spyder007** [comment]
Ditto:  I installed the docker container as a pod, keep getting a timeout looking for the password box (which seems to indicate it's entering the email but cannot find the password box)

**Comment by jasonsf** [comment]
This looks like a puppeteer issue. Does something form here help? https://github.com/puppeteer/puppeteer/issues/3323

**Comment by Vendo232** [comment]
First, thank you! Great work.

Second getting this error:

 TimeoutError: Waiting for selector `#passwd` failed: Waiting failed: 30000ms exceeded. Next update at 8:50:24 AM

    
Will check the puppeteer

**Comment by zachowj** [comment]
The playwright branch is a complete rewrite of the xfinity code and works 99% of the time in my dev environment but works only 1% of the time in production.

**Comment by zachowj** [comment]
take a look at #104
